### ISSUE TITLE
Show heart rate in Stats View

### ISSUE THREAD

**Issue by randomC0der** [SK1Y101/PoketchFitbit#15]
**Describe the solution you'd like**

You can see your steps both in the pedometer view and in the stats view. Instead of showing duplicated information you could show the heart rate. (Note: needs an additional permission)

The HP bar could be filled relative to your max heart rate. (formula: 220 - age)

Here is a mock-up how the final stats view could look like:
![grafik](https://user-images.githubusercontent.com/39627670/153228870-bb169664-90a5-4024-aac2-392066f23040.png)

**Additional context**

I use the original Versa.

**Comment by SK1Y101** [comment]
That is a really good idea! I think I'll implement that sometime this week
I believe the api exposes the property user.maxHeartRate which I can use here too

**Comment by SK1Y101** [comment]
@randomC0der Thanks again for the awesome idea! I've finalised all testing on my end and submitted the updated version of the application to fitbit. Hopefully they'll push the update in a few days.

**Comment by SK1Y101** [comment]
App update has been pushed, should now be available by updating within the FitBit app.
