### ISSUE TITLE
Issue with entire interface

### ISSUE THREAD

**Issue by midnight8dragon** [SK1Y101/PoketchFitbit#30]
The interface has reverted to it's original colors and will not swap between apps anymore. It will only show the clock section. I've tried to change it in the fitbit app, but nothing is changing.

**Comment by TruePikachu** [comment]
I can confirm this with my Sense.

The only setting that seems to have any effect right now is the face shape/style (_not_ color).

**Comment by marielatte88** [comment]
Me too, i can't change the color of the watch & i can't swap with another features.. it only display clock section

**Comment by SK1Y101** [comment]
I've seen that same problem crop up when testing, it's usually a result of the UI code not being correctly implemented.

I did recently push an update to the watch, a bug or two probably slipped through.

FitBit themselves tested and allowed it to be published, so I'm not sure how it got passed them.

I'll quickly hop back into my development area, revert changes, and ask Fitbit to push that through. Should be a few days before I can figure out exactly what's causing the problem and reintroduce the update.

Sorry that this has happened, completely unprecedented.

**Comment by SK1Y101** [comment]
I've submitted the revert to FitBit, hopefully that gets pushed to everyone as soon as possible. I'm terribly sorry again to everyone for this.

**Comment by midnight8dragon** [comment]
> I've submitted the revert to FitBit, hopefully that gets pushed to everyone as soon as possible. I'm terribly sorry again to everyone for this.
> 
> Just to verify, @TruePikachu, you're using a Sense, @marielatte88 and @midnight8dragon are the two of you using either a Sense or Versa 3, as that would narrow down the bug to where I think it is

I also have a Sense, and as @TruePikachu stated "The only setting that seems to have any effect right now is the face shape/style (not color)." Also, I appreciate how quickly you got back to us! :)

**Comment by SK1Y101** [comment]
I've fixed what I believe to be the problem. The fitbit OS Simulator isn't showing any abnormal behaviours.

I'll push this fix back to fitbit, and they'll hopefully push it through quickly.
I'll leave this issue open until it's been verified to work

**Comment by midnight8dragon** [comment]
> Just a heads up @marielatte88, @midnight8dragon, and @TruePikachu, FitBit has accepted my update, I hope this has restored functionality to your watches?

It appears to be working for me after I updated the app in the fitbit application!

**Comment by TruePikachu** [comment]
This particular issue is resolved for me, though I'm about to open one up for another problem (which existed before the problematic update, but is especially revealed with the new documentation).

**Comment by SK1Y101** [comment]
sounds good!

**Comment by tango-fox7** [comment]
Same thing happens to me with a versa 4. Watch crashes every time I customize the screen and then reverts back to original colors. Both app and Fitbit up to date. I love this screen and am super disappointed that it doesn’t work ToT
