### ISSUE TITLE
(Sense) Long press actions don't work due to OS intercept

### ISSUE THREAD

**Issue by TruePikachu** [SK1Y101/PoketchFitbit#33]
On the Sense (at minimum), a long press on the clock face (I haven't measured the actual duration, but I can do experiments if desired) automatically starts the "Clocks" built-in applet, which is used to switch the clock face. From what I can determine, this can't be disabled through a setting on either the watch or mobile app. As a result, all functionality that involves a long press on affected platforms is effectively broken.

Assuming this can't be overridden from the code's side, a possible workaround would be to offer an option to adjust how long a tap needs to be to be considered a long tap, as well as the option to enable the use of a double tap (which can use the length adjustment to determine how quick the double tap needs to be to activate).

**Comment by SK1Y101** [comment]
Thanks for the information, I had no idea this was a feature of the newer devices.
I'll see what the FitBit SDK documentation has to offer on the matter, then figure out a fix for this.
As far as I am aware, there isn't a way to override this behaviour with clock-face code on the sense, but I could be mistaken.

As to your first work-around idea, I could (probably) implement both with relative ease, and allow the user to select how they interact with the secondary functionality of a button in the settings app. This would probably be how I would implement it even if I could somehow override the default behaviour.

**Comment by SK1Y101** [comment]
I'm going to keep this open while I wait for the fitBit review team to push the update

**Comment by SK1Y101** [comment]
@TruePikachu The update was pushed through earlier today, I hope everything is working correctly.

**Comment by SK1Y101** [comment]
Well, No-one has complained about this being an issue, So I'll assume it fixed for now
