### ISSUE TITLE
Fitbit Versa 2 - label: not available

### ISSUE THREAD

**Issue by Lostdelirium** [SK1Y101/PoketchFitbit#40]
**Describe the bug**
Unable to install from shop app onto Versa 2.

**To Reproduce**
Open fitbit app
Go to clocks/apps
Search Poketch
Open watchface
Unable to click install. 
Label: not available (due to firmware maybe?) 

**Expected behavior**
Expected to be able to install. 

**Screenshots**
![Screenshot_20220528-153809](https://user-images.githubusercontent.com/28832958/170812932-a15aab78-965e-4b39-8446-0fca4ceaf932.png)
![IMG_20220528_153915](https://user-images.githubusercontent.com/28832958/170812938-a92ec06c-ba73-4dfd-869b-7bbaebd3f3e8.jpg)

**Smartphone (please complete the following information):**
 - Device: [pixel 4xl]
 - OS: [GraphneOS]
 - Browser [Chrome ]

**Additional context**
Possible firmware clash? Unsure.

**Comment by Lostdelirium** [comment]
Issue has resolved itself and was able to install watch face today.

Thankyou!

**Comment by SK1Y101** [comment]
Seems a bit strange that this happened, but I'm glad it was resolved!

**Comment by SK1Y101** [comment]
Hey @Lostdelirium, did you ever figure out what the root cause of this issue was?
Having a repeatable fix would be great
