### ISSUE TITLE
Customization broken on Versa 4

### ISSUE THREAD

**Issue by natalieduong** [SK1Y101/PoketchFitbit#43]
In the settings, I tried to change the customization of the face. However, it doesn't update on the device even with restarting the app, syncing, and switching faces.

**Comment by edraft** [comment]
Same on Versa 2

**Comment by SK1Y101** [comment]
I've found the same with multiple watch faces, not just this.
Restarting my versa and app a few times normally fixes it for a few weeks.
I've tried debugging on the clockface side, but this seems to be a fitbit infrastructure problem ):
