### ISSUE TITLE
Poketch app ideas

### ISSUE THREAD

**Issue by EmeraldTheNinja** [SK1Y101/PoketchFitbit#56]
App ideas

 - In Pokemon Platinum there was an unused app that functioned like a stopwatch.
The stopwatch featured a voltorb style button that when pressed, started and stopped a stopwatch. I would really like to see this added if possible

- The calculator is another app that I thought could be added I know there is a Fitbit app for calculator but you have a timer on there too

- Coin flip is one of my most wanted poketch apps I would like to see implemented. One because I won't need a coin anymore for tough decisions and two the little Magikarp is so cute 🥰

Another thing, please make it so only the button switches the poketch app. When I swipe down with my Versa 2 to get to my phone notifications it goes from the digital clock to the Snorlax timer, and its driving me crazy switching back between the two. Maybe there could be a setting?

Overall looks fantastic, never changing clocks

**Comment by SK1Y101** [comment]
Hi @EmeraldTheNinja 
While those app ideas sound great, and I'd love to have more functionality, the watch face as it stands already uses 64072Bytes out of the 65528Byte limit for the Javascript.
It's possible in theory to slim that down slightly, but I don't see there being enough gains to implement all three. (It's possible you could squeeze a small app in, but something like a calculator is going to be huge)

**Comment by EmeraldTheNinja** [comment]
> Hi @EmeraldTheNinja While those app ideas sound great, and I'd love to have more functionality, the watch face as it stands already uses 64072Bytes out of the 65528Byte limit for the Javascript. It's possible in theory to slim that down slightly, but I don't see there being enough gains to implement all three. (It's possible you could squeeze a small app in, but something like a calculator is going to be huge)

I didn't know there was a limit. But what about changing how the button to switch poketch apps works to make it easier to swipe down to get my notifications, would that be too much to add?
I'm new to GitHub, so all of this is a bit much to wrap my head around how everything works.
