### ISSUE TITLE
Snorlax timer bug

### ISSUE THREAD

**Issue by EmeraldTheNinja** [SK1Y101/PoketchFitbit#57]
**Describe the bug**
If you press the reset button multiple times it duplicates the arrow flashing

**To Reproduce**
1. Go to the clock
2. Click on the up button
3. Press on the reset button (2 times should do it)
4. 🐛

**Comment by SK1Y101** [comment]
Hey @EmeraldTheNinja, thanks for the contribution. I've (hopefully) fixed this in the QoL pull request #58.
If you'd like to test it, the experimental builds are linked there!

**Comment by EmeraldTheNinja** [comment]
It works!!
